const leaderboardData = {
  riders: [
    {
      id: 1,
      name: "John Doe",
      location: "5 miles",
      age: 28,
      participationBadge: 5,
      quizMaster: 3,
      topContributor: 7,
    },
    {
      id: 2,
      name: "Jane Smith",
      location: "10 miles",
      age: 32,
      participationBadge: 4,
      quizMaster: 5,
      topContributor: 6,
    },
    {
      id: 3,
      name: "John Perry",
      location: "8 miles",
      age: 38,
      participationBadge: 2,
      quizMaster: 4,
      topContributor: 9,
    },
    {
      id: 4,
      name: "Jill Seagers",
      location: "15 miles",
      age: 48,
      participationBadge: 5,
      quizMaster: 13,
      topContributor: 4,
    },
    {
      id: 5,
      name: "Gloria Pang",
      location: "17 miles",
      age: 58,
      participationBadge: 5,
      quizMaster: 9,
      topContributor: 17,
    },
    {
      id: 6,
      name: "Danny Hagehassan",
      location: "25 miles",
      age: 25,
      participationBadge: 5,
      quizMaster: 20,
      topContributor: 26,
    },
    {
      id: 7,
      name: "Zac Jackson",
      location: "35 miles",
      age: 61,
      participationBadge: 28,
      quizMaster: 35,
      topContributor: 10,
    },
  ],
  drivers: [
    {
      id: 1,
      name: "Mike Johnson",
      location: "3 miles",
      age: 45,
      participationBadge: 6,
      quizMaster: 4,
      topContributor: 8,
    },
    {
      id: 2,
      name: "Emily Davis",
      location: "8 miles",
      age: 27,
      participationBadge: 7,
      quizMaster: 1,
      topContributor: 9,
    },

    {
      id: 3,
      name: "Abbey Smith",
      location: "15 miles",
      age: 37,
      participationBadge: 2,
      quizMaster: 6,
      topContributor: 5,
    },

    {
      id: 4,
      name: "Bob Isenberg",
      location: "11 miles",
      age: 57,
      participationBadge: 7,
      quizMaster: 6,
      topContributor: 9,
    },

    {
      id: 5,
      name: "Albert Lee",
      location: "4 miles",
      age: 33,
      participationBadge: 5,
      quizMaster: 2,
      topContributor: 8,
    },

    {
      id: 6,
      name: "Sarah Sanders",
      location: "13 miles",
      age: 41,
      participationBadge: 5,
      quizMaster: 6,
      topContributor: 16,
    },

    {
      id: 7,
      name: "Peter Takas",
      location: "19 miles",
      age: 67,
      participationBadge: 7,
      quizMaster: 12,
      topContributor: 10,
    },
  ],
};

export default leaderboardData;
